# 标签页图标
favicon:
  type: "image/x-icon"
  href: "/favicon.ico"

# html lang
language: en-us

# canvas 动态背景
canvas_dust: true

# <body> 背景图片链接
background_image:
  dark: https://ak.hypergryph.com/assets/index/images/ak/pc/bk.jpg # 暗色模式
  light: /img/bk.jpg # 亮色模式

# 侧边栏
aside:
  in_left: false # 侧边栏在左 true / false
  logo: https://ak.hypergryph.com/assets/index/images/ak/pc/faction/1.png #图片链接，建议 1:1 比例
  logo_margin: 0 # 为 Logo 图片设置 CSS margin 属性值，参考：https://developer.mozilla.org/zh-CN/docs/Web/CSS/margin
  logo_border_radius: 0 # CSS border-radius 的属性值，参考：https://developer.mozilla.org/zh-CN/docs/Web/CSS/border-radius
  dr: https://github.com/Yue-plus # 侧边栏 Dr. 链接
  block_in_top: false # 目前为侧边栏文章目录置顶
  # icp: 赣ICP备19008355号 # ICP 备案号，与版权声明相同，但会链接到 https://beian.miit.gov.cn/
  copyright: # 版权声明、备案号等，可自定义键值，不想显示则留空
    ©: 1970 to 2025

# 社交链接
# 格式：链接 || 图标
social:
  GitHub: https://github.com/Yue-plus || fab fa-github
  E-Mail: mailto:Yue_plus@foxmail.com || fa fa-envelope
  BiliBili: https://space.bilibili.com/28606851 || fa-brands fa-bilibili
  # Weibo: https://weibo.com/yourname || fab fa-weibo
  # Zhihu: https://www.zhihu.com/people/yourname || fab fa-zhihu

# post 文章页面配置；true / false
post:
  date: true # 是否显示发布日期
  updated: true # 是否显示修改日期
  source: false # 是否显示源文件路径
  word_count: true # 是否显示字数统计
  reading_time: true # 是否显示预计阅读时长
  excerpt: true # 是否在文章中显示摘要内容（<!-- more--> 以上的内容）
  reward: # 文章末显示打赏二维码
    支付宝 | Alipay: img/Alipay.png
    微信 | Wechat: img/WeChat.png
  count: true # 是否显示字数统计
  time: true # 是否显示预计阅读时长

# 文章内目录
toc:
  list_number: true # true / false ；是否显示编号
  max_depth: 6 # 最大目录深度
  min_depth: 1 # 最小目录深度
# 归档页；true / false
archives:
  categories_count: true # 是否显示分类总数
  tags_count: true # 是否显示标签总数

# 搜索
search:
  enable: true
  content: true # 若为 false，仅可搜索标题及 metadata
  preload: false # 自动加载搜索数据
  # 设为 post 时，仅可搜索 post 页面
  # 设为 page 时，仅可搜索非 post 页面
  # 设为 all 时，可搜索全部页面
  field: post
  # 设为 html 时，依据 html 文件生成
  # 设为 striptags 时，滤除 html tag
  # 设为 raw 时，依据 markdown 源文件生成
  format: striptags

# Vercount
# 详见 https://vercount.one/
vercount:
  enable: true
  showPV: true # Page View 单个用户连续点击 n 篇文章，记录 n 次访问量。
  showUV: true # Unique Visitor 单个用户连续点击 n 篇文章，只记录 1 次访客数。

# Valine
# 详见 https://valine.js.org
valine:
  enable: true
  app_id: LSe7mf1XYliLqgIrc3jlqXfT-gzGzoHsz # <APP ID>
  app_key: Fu9giJfnidkCamaW89FUpidw # <APP KEY>

# gitalk
# 详见 https://github.com/gitalk/gitalk
gitalk:
  enable: true
  client_id: 2beac2cf86ee679d97a7 # GitHub Application Client ID
  client_secret: fdf2eb7803b21867d7737011667fe1b00f0b3be0 # GitHub Application Client Secret
  repo: GitalkTest # GitHub repository
  owner: Yue-plus # GitHub repository owner
  admin: ["Yue-plus"] # GitHub repository owner and collaborators (Users who having write access to this repository)
  # Example: [adminA,adminB]
  id: location.pathname # (optional) The unique id of the page
  # Example: location.pathname

#Artalk
#详见：https://artalk.js.org/
artalk:
  enable: false
  server: https://artalk.server.instance/ # 你的 Artalk 服务地址
  site_name: My Blog # 站点名称，用于区分多个站点（可选）

# 图表支持
mermaid:
  enable: true
  version: "8.13.5"

# main menu navigation
menu:
  Home: ""
  #  About: about/
  #  Contact: contact/
  Archives: archives/
  独立页面: demo/
  贡献者: contributors/

# pjax 支持
pjax:
  enable: true

# stylesheets loaded in the <head>
stylesheets:
  - //unpkg.com/@highlightjs/cdn-assets@11.4.0/styles/atom-one-dark-reasonable.min.css

# scripts loaded in the end of the body
scripts:
  - //unpkg.com/@highlightjs/cdn-assets@11.4.0/highlight.min.js
